openapi: 3.1.0
info:
    title: API docs
    version: 1.0.0
    description: |
        Api document.

paths:
    /users/sign-in:
        post:
            summary: Sign in
            tags:
                - users
            description: |
                Returns a random number. Placeholder sign-in endpoint.
            responses:
                "200":
                    description: Successfully signed in
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SignIn"
                "500":
                    description: Internal server error

    /users/me:
        get:
            summary: who am i
            tags:
                - users
            security:
                - BearerAuth: []
            description: |
                Returns user information
            responses:
                "200":
                    description: Successfully signed in
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Me"

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: auth token

    schemas:
        SignIn:
            type: object
            properties:
                num:
                    type: integer
                    format: int64
                    minimum: 0

        Me:
            type: object
            properties:
                id:
                    type: integer
